[package]
name = "aoc"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[[bin]]
name = "2022_1"
path="src/2022/1.rs"



[dependencies]
clap = { version = "4.0", features = ["derive"]}